config.action_mailer.delivery_method = :imap
config.action_mailer.smtp_settings = {
  :address              => "mail.2gen.net",
  :port                 => 143,
  :domain               => 'ecotest.w2gen.webfactional.com',
  :user_name            => 'w2gen',
  :password             => '21rebeCC@$T',
  :authentication       => 'plain',
  :enable_starttls_auto => true  }